### ISSUE TITLE
How Can I view an array inside a subChild ?

### ISSUE THREAD

**Issue by cs4alhaider** [cenksk/CITreeView#3]
Hi ,
Thank you for this framework , it's so helpful !
------------------
I'm trying to show an array of values inside a subChild (one value in it's own cell) and i can't figure it out yet

In a normal tableView it would be like :
myLabel.text = myArray[indexPath.row]

Is it possible to do that ?
Check my demo project to see what i'm trying to explain and you can see my data from the api link:
https://github.com/cs4alhaider/URL-analytics

**Comment by cenksk** [comment]
Hi,
I downloaded your code and i review it. Actually, you don't need to use CITreeViewData you can put your JSON data in an array after downloaded with AFNetworking and you just teel to CITreeView something like that,

func treeViewDataArray() -> [Any] {
        return analyticsArray
    }

 func treeViewSelectedNodeChildren(for treeViewNodeItem: Any) -> [Any] {
        if let dataObj = treeViewNodeItem as? MyAnalyticsData {
            return dataObj.references (or platforms or countries vb.)
        }
        return []
        
    }

**Comment by cs4alhaider** [comment]
I have tried to implement it but i didn't know how to do it correctly
I will appreciate if you can sent a pull request 🙏

**Comment by cs4alhaider** [comment]
I have commit my last edit on :
https://github.com/cs4alhaider/URL-analytics

**Comment by cenksk** [comment]
I cant read the whole code now but if you try to manipulate your json like this;

let urlJSON : JSON = JSON(responds.result.value!)
                
                for element in urlJSON {
                    let ciTreeViewData = CITreeViewData(name: element.0)
                    for element1 in element.1 {
                        let ciTreeViewData2 = CITreeViewData(name: element1.0)
                        ciTreeViewData.addChild(ciTreeViewData2)
                    }
                    allJSONArray.append(ciTreeViewData)
                }

PS: element.1 or element.0 are bad using you can use much more better way but generally logic is something like that
